# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9cf4e0e7fddde0e1ca14fb4bb437c490ca36d546e5833e88710c69e161cca1a34baa5588077735ab879b2bcb51cb901b3cf1e94036ab330a1279ea73adf64b9e

test:
  secret_key_base: e65d06be9884f6aa6057cbf8377d7ad5ca7c2208fa70c656dd93527798cb063ff4f02aa5d149a810d9e8432f4cba04e5e059c7c841871494cc1eb42479eb8d92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
